### ISSUE TITLE
Can we have this feature, please!

### ISSUE THREAD

**Issue by ArnoJuan** [ericchu94/arn#1]
Can we have a version with local upload arm9loaderhax.bin, without though http://astronautlevel2.github.io/AuReiNand/

**Comment by ericchu94** [comment]
You mean the payload with the path set to arm9loaderhax.bin, or an upload, change path, then download feature?

**Comment by ArnoJuan** [comment]
Yes! Because i will build AureiNand myself.
So I have a original arm9loaderhax.bin need to change path.
Can have this feature?

**Comment by ericchu94** [comment]
I don't think I want to support this feature. If you can build AuReiNand by yourself, then you can also build and run `pathchanger` by yourself: `make pathchanger`

**Comment by ArnoJuan** [comment]
That's right! Sorry about my stupid! Thank you:)
