### ISSUE TITLE
[Suggestion] Move away from scanf

### ISSUE THREAD

**Issue by ghost** [ericchu94/arn#2]
Scanf is not a safe function, especially on a server. I would recommend switching away from it to a more safe function.

**Comment by ericchu94** [comment]
Where am I using scanf?

**Comment by ghost** [comment]
Server backend. The ARN path changer? Unless you made a custom one..

**Comment by ericchu94** [comment]
I ported pathchanger to node 3 days ago: dc4fd081169de3f99917d5d26a39e0f026507fd9
