### ISSUE TITLE
[Suggestion] Fetch URL Parameters / Permalink

### ISSUE THREAD

**Issue by usagirei** [ericchu94/arn#3]
If possible, perhaps pull the parameters from url parameters / route parameters and redirect to the download link directly, allowing for quick bookmarks of patched payload

Perhaps add a "permalink" button when editing the fields that points to the url like

`http://luma3ds.ericchu.net/?build=nightly&path=anim/arm9payload.bin`
`http://luma3ds.ericchu.net/?build=stable&path=a9lh/Luma3DS.bin`
or
`http://luma3ds.ericchu.net/#!/nightly/anim/arm9payload.bin`
`http://luma3ds.ericchu.net/#!/afc6f51/arm9select/default.bin`

**Comment by ericchu94** [comment]
My links currently are as follows:
`http://luma3ds.ericchu.net/release/anim/arm9payload.bin`
`http://luma3ds.ericchu.net/latest/a9lh/Luma3DS.bin`
With latest being the latest commit

I don't know if I want to support arbitrary commits and I don't want to support arbitrary releases, but if you would like those features, please make another issue for it, and we can discuss it there.

 I definitely can add a permalink option, in the form of adding a "Generate Link" button

**Comment by usagirei** [comment]
Oh, so it was there already, then it was just missing a way to easily get the link for it, the arbitrary commits is not really necessary since you'll probably be using the latest ones anyway.

**Comment by ericchu94** [comment]
Generate link button added and is live.

**Comment by usagirei** [comment]
Thanks!
This should make updating luma payloads faster until bootAnim9 can do the pathchanger itself
